# Generated by Django 5.0.2 on 2024-06-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_remove_product_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
