# Generated by Django 5.0.2 on 2024-06-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_alter_product_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
