# Generated by Django 5.0.2 on 2024-09-18 08:00

from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce', '0012_order_complete'),
    ]
    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='email_address',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
